timezone: "Europe/Madrid"

institutions:
  - id: "mpm"
    enabled: true
    name: "Museo Picasso Málaga"
    type: "Museo de arte"
    base_url: "https://www.museopicassomalaga.org/"
    tickets_url: "https://www.museopicassomalaga.org/es/visita"
    exhibitions_url: "https://www.museopicassomalaga.org/"
    activities_url: "https://tickets.museopicassomalaga.org/es/854-actividades"
    rss_exhibitions_url: ""
    rss_activities_url: ""

  - id: "thyssen"
    enabled: true
    name: "Museo Carmen Thyssen Málaga"
    type: "Museo de arte"
    base_url: "https://carmenthyssenmalaga.org/"
    tickets_url: "https://www.carmenthyssenmalaga.org/horarios-tarifas-ubicacion"
    exhibitions_url: "https://carmenthyssenmalaga.org/exposiciones-temporales"
    activities_url: "https://carmenthyssenmalaga.org/actividades"
    rss_exhibitions_url: ""
    rss_activities_url: ""
