timezone: "Europe/Madrid"

institutions:
  - id: "mpm"
    enabled: 1
    name: "Museo Picasso Málaga"
    type: "Museo de arte"
    base_url: "https://www.museopicassomalaga.org/"
    tickets_url: "https://www.museopicassomalaga.org/es/visita"
    exhibitions_url: "https://www.museopicassomalaga.org/exposiciones"
    activities_url: "https://www.museopicassomalaga.org/actividades"
    rss_exhibitions_url: ""
    rss_activities_url: ""

  - id: "thyssen"
    enabled: 0
    name: "Museo Carmen Thyssen Málaga"
    type: "Museo de arte"
    base_url: "https://carmenthyssenmalaga.org/"
    tickets_url: "https://www.museopicassomalaga.org/horarios-tarifas-ubicacion"  # <- no importa si está desactivado
    exhibitions_url: "https://carmenthyssenmalaga.org/exposiciones-temporales"
    activities_url: "https://carmenthyssenmalaga.org/actividades"
    rss_exhibitions_url: ""
    rss_activities_url: ""
