name: Collect cultural events

on:
  schedule:
    - cron: '0 4 * * *'   # 06:00 Madrid aprox en verano
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: collect
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 1) Sincroniza ANTES de generar nada (árbol limpio)
      - name: Sync branch (pre-collect)
        run: |
          set -e
          BRANCH="${GITHUB_REF_NAME:-main}"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git fetch origin "$BRANCH"
          git pull --rebase --autostash origin "$BRANCH"

      # 2) Preflight: compila collect.py para pillar errores de pegado/indentación
      - name: Preflight (compile collect.py)
        run: |
          python - <<'PY'
          import py_compile, sys
          py_compile.compile('scripts/collect.py', doraise=True)
          print('collect.py OK')
          PY

      # 3) Ejecuta el recolector (sin -m, directo)
      - name: Run collector
        env:
          PYTHONPATH: .
        run: |
          python scripts/collect.py

      # 4) Commit & push
      - name: Commit & push changes
        run: |
          set -e
          BRANCH="${GITHUB_REF_NAME:-main}"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/events.json data/meta.json || true

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: update events.json [skip ci]"

          git fetch origin "$BRANCH"
          git pull --rebase --autostash origin "$BRANCH"

          git push origin HEAD:"$BRANCH"
