name: Collect Events (MPM + Thyssen)

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Collect
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python scripts/collect.py
        run: python -m scripts.collect

      - name: Commit & push build
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f build/events.json
          git commit -m "chore: update events.json [skip ci]" || echo "No changes"
          git push
