name: Collect cultural events

on:
  schedule:
    - cron: '0 4 * * *'  # 06:00 Europe/Madrid (UTC+2 in summer)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: collect
  cancel-in-progress: true

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run collector
        run: |
          python scripts/collect.py
      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/events.json data/meta.json || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update events.json [skip ci]"
            git push
          else
            echo "No changes to commit"
          fi
